More githooks

diff --git a/git_prepush_hook b/git_prepush_hook
--- a/git_prepush_hook
+++ b/git_prepush_hook
@@ -1,54 +1,52 @@
 #!/bin/sh
 
-# An example hook script to verify what is about to be pushed.  Called by "git
-# push" after it has checked the remote status, but before anything has been
-# pushed.  If this script exits with a non-zero status nothing will be pushed.
-#
-# This hook is called with the following parameters:
-#
-# $1 -- Name of the remote to which the push is being done
-# $2 -- URL to which the push is being done
-#
-# If pushing without using a named remote those arguments will be equal.
-#
-# Information about the commits which are being pushed is supplied as lines to
-# the standard input in the form:
-#
-#   <local ref> <local sha1> <remote ref> <remote sha1>
-#
-# This sample shows how to prevent push of commits where the log message starts
-# with "WIP" (work in progress).
-
 remote="$1"
 url="$2"
-
 read local_ref local_sha remote_ref remote_sha
 
-echo "local_ref: $local_ref, local_sha: $local_sha, remote_ref: $remote_ref, remote_sha: $remote_sha"
 
-if [ "$local_sha" = "" ]
-then
-    echo "No pending commits found!"
-else
-    echo "Commits pending:"
-    #echo "$(git log --oneline $remote..HEAD)"
-    echo "$(git log --oneline $remote_sha..$local_sha)"
-    echo ""
-
-    exec < /dev/tty # eww
-    read -p "Are you sure you want to push (y/n)? " choice
-
-    case "$choice" in
-        y|Y|yes|Yes|YES ) choice="yes";;
-        n|N|no|No|NO ) choice="no";;
-        * ) echo "invalid option"; exit 1;;
-    esac
-
-    if [ "$choice" = "no" ]
-    then
-        exit 1
+# Don't push if you have invalid error codes set
+# NOTE: The check runs against your currently checked out code, even if you are
+# trying to push a different branch
+check_error_codes() {
+    output=$(python buildscripts/errorcodes.py)
+    RETVAL=$?
+    if [ $RETVAL -ne 0 ]; then
+        echo "$output"
+        echo -n "Error codes problem detected in currently checked out branch; "
+        echo "aborting push. To push anyway use --no-verify"
+        exit $RETVAL
     fi
+}
 
-fi
+# Lists the commit messages for the commits being pushed and promts the user for
+# confirmation before pushing.
+# NOTE: Getting the list of commits to be pushed can fail if the base commit on
+# the remote isn't a direct ancestor of the commits staged in your local repo.
+check_pending_commit_messages() {
+    if [ "$local_sha" = "" ]
+    then
+        echo "No pending commits found!"
+    else
+        echo "Commits pending:"
+        echo "$(git log --oneline $remote_sha..$local_sha)"
+        echo ""
 
-exit 0
+        exec < /dev/tty # eww
+        read -p "Are you sure you want to push (y/n)? " choice
+
+        case "$choice" in
+            y|Y|yes|Yes|YES ) choice="yes";;
+            n|N|no|No|NO ) choice="no";;
+            * ) echo "invalid option"; exit 1;;
+        esac
+
+        if [ "$choice" = "no" ]
+        then
+            exit 1
+        fi
+    fi
+}
+
+check_error_codes
+check_pending_commit_messages
